apiVersion: v1
kind: Secret
metadata:
  name: mariadb-passwords
  namespace: wordpress
type: Opaque
stringData:
  # Identifiants principaux
  mariadb-root-password: "root_P@ss123"
  mariadb-password: "user_P@ss123"

  # Pour l'outil mariabackup (utilisé pour le SST/IST entre les nœuds)
  mariadb-galera-mariabackup-password: "maria_Repli123"
