## Configuration de l'image (Legacy pour la compatibilité)
image:
  repository: bitnamilegacy/minio
  tag: 2024.11.7-debian-12-r0

## Mode Haute Disponibilité (Distributed)
# MinIO nécessite 4 nœuds pour l'Erasure Coding (résilience des données)
mode: distributed
replicas: 4

## Désactiver le déploiement de la console séparée
# On préfère l'interface intégrée au serveur pour éviter les problèmes de routage
console:
  enabled: false

## Activer l'interface utilisateur intégrée
api:
  browser: "on"

## Authentification
auth:
  rootUser: "admin-ha"
  rootPassword: "mini0_1234"

## Persistance via Longhorn
persistence:
  enabled: true
  storageClass: "longhorn"
  size: 5Gi  # 5Gi minimum recommandé pour éviter les erreurs de quorum disque

## Anti-affinité SOFT
# Obligatoire : tu as 4 pods mais seulement 3 nœuds physiques.
# Cela permet à 2 pods de cohabiter sur une même VM.
podAntiAffinityPreset: soft

## Configuration du Service (Accès externe via NodePort)
service:
  type: NodePort
  ports:
    api: 9000
    console: 9001
  nodePorts:
    api: 30090
    console: 30091

## Variables d'environnement pour stabiliser l'URL de l'interface
extraEnvVars:
  - name: MINIO_SERVER_URL
    value: "http://192.168.90.10:30090"
  - name: MINIO_BROWSER_REDIRECT_URL
    value: "http://192.168.90.10:30091"
  - name: MINIO_API_PORT
    value: "9000"
  - name: MINIO_CONSOLE_PORT
    value: "9001"

## Ressources (Pour éviter que MinIO ne consomme toute la RAM des VMs)
resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m
