apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: wordpress
type: Opaque
stringData:
  # MariaDB
  mariadb-password: "userPass123!"
  mariadb-root-password: "rootPass123!"

  # WordPress admin
  wordpress-password: "wpPass123!"

  # Redis
  redis-password: "redisPass123!"

  # MinIO (pour le plugin S3)
  minio-access-key: "wp-user"
  minio-secret-key: "wp-secret-password"
