apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: wordpress
type: Opaque
stringData:
  # MariaDB
  mariadb-password: "user_P@ss123"
  mariadb-root-password: "root_P@ss123"

  # WordPress admin
  wordpress-password: "us€rP@ss"

  # Redis
  redis-password: "R€disP@ss123"

  # MinIO (pour le plugin S3)
  minio-access-key: "wp-user"
  minio-secret-key: "wp-secret-password"
