# =============================================================================
# COUCHE 0 — NAMESPACE
# =============================================================================
# Tous les composants du stack MySQL HA vivent dans ce namespace.
# Le label "app.kubernetes.io/part-of" permet de regrouper les ressources
# dans les outils de monitoring (Lens, k9s, etc.)
# =============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
  labels:
    app.kubernetes.io/part-of: wordpress-stack
    environment: production
