apiVersion: v1
kind: Secret
metadata:
  name: mariadb-passwords
  namespace: wordpress
type: Opaque
stringData:
  # Mot de passe ROOT (Admin)
  mariadb-root-password: "root_P@ss123"

  # Mot de passe Utilisateur (WordPress)
  mariadb-password: "user_P@ss123"

  # Mot de passe Réplication Galera (Clé exacte de votre ancien script)
  mariadb-galera-mariabackup-password: "maria_Repli123"

  # Doublon de sécurité (parfois requis par les nouvelles versions du chart)
  mariadb-galera-password: "maria_Repli123"
