# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # Définition de nos 3 clusters indépendants (Nom => Fin de l'adresse IP)
  clusters = {
    "k8s-hub"     => "10",
    "k8s-staging" => "11",
    "k8s-prod"    => "12"
  }

  clusters.each do |name, ip_suffix|
    config.vm.define name do |node|
      node.vm.box = "ubuntu/jammy64"
      node.vm.box_version = "1.0"
      node.vm.network "private_network", type: "static", ip: "192.168.98.#{ip_suffix}"
      node.vm.hostname = name
      node.vm.disk :disk, size: "60GB", primary: true
      node.vm.provider "virtualbox" do |v|
        v.name = name
        v.memory = 8192
        v.cpus = 2
      end
      
      node.vm.provision :shell do |shell|
        shell.path = "install_kubernetes.sh"
        shell.args = ["master", "192.168.98.#{ip_suffix}"]
      end
    end
  end
end
