apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-ha
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.4-php8.2-fpm-alpine # Version légère
        env:
        - name: WORDPRESS_DB_HOST
          value: "wp-db-haproxy" # Notre cluster Percona
        - name: WORDPRESS_DB_USER
          value: "wp_user"
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-db-secrets
              key: users
        # Les réglages Redis pour WordPress
        - name: WORDPRESS_CONFIG_EXTRA
          value: |
            define('WP_REDIS_SENTINEL', 'wp-redis-sentinel');
            define('WP_REDIS_SERVERS', ['rfr-wp-redis:26379']);
